### PR TITLE
Set profile

### PR DESCRIPTION
**Pull request by minju25kim**
- added edit route
- added access verification for edit
- update profile picture

### CODE REVIEW

**Comment by sonianb** [comment]
[Display groups that user has joined on the landing page](https://trello.com/c/wycmXjbf/76-display-groups-that-user-has-joined-on-the-landing-page)

**Comment by sonianb** [comment]
[Allow users to edit their profiles](https://trello.com/c/4XkoZUBz/79-allow-users-to-edit-their-profiles)

**Comment by sonianb** [comment]
[User needs to create a profile when they first sign up](https://trello.com/c/eOwbBltK/72-user-needs-to-create-a-profile-when-they-first-sign-up)

**Review by alternadiva — APPROVED** [review]

**Review by alternadiva — COMMENTED** [review]
Great work on the user profile update and great progress on the location setter 🤩

**Review by AsmahanM — APPROVED** [review]

**Pull request merged**
